$(function(){
	$("#formLogin").show();
	$("#formRegister").hide();
	$("#btnShowRegister").on("click",function(){
			$("#formLogin").hide();
	$("#formRegister").show();
	});
	$("#btnShowLogin").on("click",function(){
	$("#formLogin").show();
	$("#formRegister").hide();
	});
	$("#btnCreateAccount").on("click",function(){
		$.post("server/register.php",$("#formRegister").serialize(),function(data,success){
			alert(data);
		});
	});
	$("#btnLogin").on("click",function(){
		$.post("server/login.php",$("#formLogin").serialize(),function(data,success){
			alert(data);
			window.location="dashboard";
		});
	});
	$("#menu-left").hide();
	var $param1=true;
	$("#tab-menu").on("click",function(){
		if($param1){
		$("#menu-left").show();
		$param1=false;
		}else{
		$("#menu-left").hide();
		$param1=true;
		}
	});
	$("#login-or-regis").on("click",function(){
		window.location="RegLog.html";
	});
	$("#menu-right").hide();
	var $param2=true;
	$("#options").on("click",function(){
		if($param2){
		$("#menu-right").show();
		$param2=false;
		}else{
		$("#menu-right").hide();
		$param2=true;
		}
	});
	$("#logReg").on("click",function(){
		window.location = "RegLog.html";
	});
	$("#navigator").on("click",function(){
		window.location = "home.html";
	});
	$("#logout").on("click",function(){
		window.location="../home.html";
	});
	$("#search-tiket").on("click",function(){
		$("#pop-search-tiket").show();
	});
	$(".popupmenu").hide();
	$(".btn-close").on("click",function(){
		$(".popupmenu").hide();
	});
	$("#btn-Find-Ticket").on("click",function(){
		var $form_find_ticket = $("#form-find-ticket").serialize();
		$.post("../server/searchTicket.php",$form_find_ticket,function(data,success){
			alert(data);
		});
	});
});